/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.checkers.options;

import com.functionalities.utilities.files.SaveGame;
import com.gui.checkers.principals.BoardGUI;
import com.gui.checkers.principals.MenuCheckersGUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author erik-lopez
 */
public class LoadGame extends javax.swing.JFrame {
    private int ID;
    private int counter;
    public static SaveGame game;
    /**
     * Creates new form LoadGame
     */
    public LoadGame() {
        ID = 0;
        initComponents();
        fillTable();
        counter = 1;
        startButton.setEnabled(false);
        this.setLocationRelativeTo(null);
    }
    
    public void fillTable(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"No.","Player 1","Player 2","Time"},MenuCheckersGUI.getGamesSaved().size());
        gamesTable.setModel(model);
        
        TableModel modelData = gamesTable.getModel();
        int counter = 1;
        for (int i = 0; i < MenuCheckersGUI.getGamesSaved().size(); i++) {
            SaveGame gameSaved = MenuCheckersGUI.getGamesSaved().get(i);
            counter += i;
            modelData.setValueAt(counter, i, 0);
            modelData.setValueAt(gameSaved.getUser1().getName(), i, 1);
            modelData.setValueAt(gameSaved.getUser2().getName(), i, 2);
            modelData.setValueAt(gameSaved.getViewTime(), i, 3);
        }
    }

    public static SaveGame getGame() {
        return game;
    }

    public static void setGame(SaveGame game) {
        LoadGame.game = game;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gamesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        infoLabel5 = new javax.swing.JLabel();
        separatorLine2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        selectButton = new javax.swing.JButton();
        infoLabel7 = new javax.swing.JLabel();
        infoLabel8 = new javax.swing.JLabel();
        infoLabel9 = new javax.swing.JLabel();
        infoLabel10 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamesTable.setBackground(new java.awt.Color(0, 102, 102));
        gamesTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        gamesTable.setFont(new java.awt.Font("Chandas", 0, 14)); // NOI18N
        gamesTable.setForeground(new java.awt.Color(255, 255, 255));
        gamesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player 1", "Player 2", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gamesTable.setRowHeight(24);
        jScrollPane1.setViewportView(gamesTable);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 590, 280));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoLabel5.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel5.setForeground(new java.awt.Color(0, 204, 204));
        infoLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel5.setText("PARTIDAS GUARDADAS");
        infoLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(infoLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 200, 30));

        separatorLine2.setBackground(new java.awt.Color(255, 255, 255));
        separatorLine2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(separatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 200, 20));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 590, 70));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startButton.setBackground(new java.awt.Color(0, 102, 153));
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        startButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel2.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 100, 100));

        selectButton.setBackground(new java.awt.Color(102, 102, 0));
        selectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        selectButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        jPanel2.add(selectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 100, 100));

        infoLabel7.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel7.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel7.setText("UNA PARTIDA");
        infoLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(infoLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 150, 30));

        infoLabel8.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel8.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel8.setText("PARTIDA");
        infoLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(infoLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 150, 30));

        infoLabel9.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel9.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel9.setText("SELECCIONE");
        infoLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(infoLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 150, 30));

        infoLabel10.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel10.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel10.setText("CARGAR");
        infoLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(infoLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 150, 30));

        background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 590, 140));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/checkersBG.jpg"))); // NOI18N
        background.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (ID == 0){
            MenuCheckersGUI menuCheckers = new MenuCheckersGUI();
            menuCheckers.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        BoardGUI board = new BoardGUI();
        board.setVisible(true);
        ID = 1;
        this.dispose();
    }//GEN-LAST:event_startButtonActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        int row = gamesTable.getSelectedRow();
        
        if (row >= 0) {
            if (counter > 0) {
                optionsGame(row);
            }
            if (counter <= 0) {
                startButton.setEnabled(true);
            }
        }

    }//GEN-LAST:event_selectButtonActionPerformed
    
    public void optionsGame(int row) {
        game = MenuCheckersGUI.getGamesSaved().get(row);
        counter = 0;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(LoadGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JTable gamesTable;
    private javax.swing.JLabel infoLabel10;
    private javax.swing.JLabel infoLabel5;
    private javax.swing.JLabel infoLabel7;
    private javax.swing.JLabel infoLabel8;
    private javax.swing.JLabel infoLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selectButton;
    private javax.swing.JSeparator separatorLine2;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
