/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gui.checkers.principals;

import com.functionalities.utilities.files.User;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author erik-lopez
 */
public class Stats extends javax.swing.JFrame {
    private int ID;
    /**
     * Creates new form Stats
     */
    public Stats() {
        initComponents();
        //showStats();
        fillTable();
        this.setLocationRelativeTo(null);
        ID = 0;
    }
    
    public void fillTable(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID","Player","Games","Won Games","Lost Games","Total Moves","Average Moves","Best Time","Best Moves"},MenuCheckersGUI.getUsers().size()); 
        statsTable.setModel(model);
        
        TableModel modelData = statsTable.getModel();
        
        for (int i = 0; i < MenuCheckersGUI.getUsers().size(); i++) {
            User user = MenuCheckersGUI.getUsers().get(i);
            modelData.setValueAt(user.getID(), i, 0);
            modelData.setValueAt(user.getName(), i, 1);
            modelData.setValueAt(user.getNumberGames(), i, 2);
            modelData.setValueAt(user.getNumberWinGames(), i, 3);
            modelData.setValueAt(user.getNumberLostGames(), i, 4);
            modelData.setValueAt(user.getTotalMoves(), i, 5);
            modelData.setValueAt(user.defineAverageMoves(), i, 6);
            modelData.setValueAt(user.getBesTime(), i, 7);
            modelData.setValueAt(user.getBestMoves(), i, 8);
        }
    }
    public void showStats() {
        ArrayList<User> users = MenuCheckersGUI.getUsers();
        System.out.println("\nEstadisticas de los jugadores: \n");
        if (users == null){
            System.out.println("El arreglo esta vacio");
        } else {
            for (int i = 0; i < users.size(); i++){
                System.out.println("---> "+users.get(i).showStats());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        infoLabel7 = new javax.swing.JLabel();
        separatorLine2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        statsTable = new javax.swing.JTable();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTES DEL JUEGO");
        setPreferredSize(new java.awt.Dimension(1080, 540));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setPreferredSize(new java.awt.Dimension(940, 540));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoLabel7.setFont(new java.awt.Font("Chandas", 3, 18)); // NOI18N
        infoLabel7.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel7.setText("ESTADISTICAS GENERALES DE LOS JUGADORES Y SUS PARTIDAS");
        infoLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(infoLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 780, 30));

        separatorLine2.setBackground(new java.awt.Color(255, 255, 255));
        separatorLine2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(separatorLine2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 720, 40));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 1030, 80));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));

        statsTable.setBackground(new java.awt.Color(0, 51, 51));
        statsTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statsTable.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        statsTable.setForeground(new java.awt.Color(255, 255, 255));
        statsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID JUGADOR", "NOMBRE", "Total Partidas", "Partidas Ganadas", "Partidas Perdidas", "Total movimientos Hechos", "Promedio mov. por partida", "Mejor Tiempo", "Mov. mejor tiempo"
            }
        ));
        statsTable.setCellSelectionEnabled(true);
        statsTable.setName("Estadisticas"); // NOI18N
        statsTable.setRowHeight(20);
        jScrollPane1.setViewportView(statsTable);

        background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 1040, 400));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/checkersBG.jpg"))); // NOI18N
        background.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (ID == 0){
            MenuCheckersGUI menuCheckers = new MenuCheckersGUI();
            menuCheckers.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Stats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel infoLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator separatorLine2;
    private javax.swing.JTable statsTable;
    // End of variables declaration//GEN-END:variables
}
