package com.gui.hanoi;

import com.gui.checkers.principals.*;
import com.functionalities.utilities.files.SaveGame;
import com.functionalities.utilities.files.Serialization;
import com.functionalities.utilities.files.User;
import com.gui.checkers.options.OptionGame;
import com.gui.general.PrincipalGUI;
import java.util.ArrayList;

/**
 * Clase del tipo frame que contiene el menu principal del juego de damas
 * 
 * @author erik-lopez
 * 
 */
public class MenuHanoi extends javax.swing.JFrame {
    
    public static ArrayList<User> usersHanoi = new ArrayList<>();
    public static ArrayList<SaveGame> gamesSavedHanoi = new ArrayList<>();
    private int ID;
    
    /**
     * Creates new form MenuGUI
     */
    public MenuHanoi() {
        initComponents();
        loadUsers();
        loadGamesSaved();
        ID = 0;
        this.setLocationRelativeTo(null);
    }
    
    public void loadUsers(){
        Serialization serialize = new Serialization();
        usersHanoi = serialize.deserializeUsers("Hanoi_users.dat");
        
        if (usersHanoi == null){
            System.out.println("El arreglo esta vacio");
        } else {
            for (int i = 0; i < usersHanoi.size(); i++){
                System.out.println("---> "+usersHanoi.get(i).showHanoi());
            }
        }
    }
    
    public void loadGamesSaved() {
        Serialization serialize = new Serialization();
        gamesSavedHanoi = serialize.deserializeGames("Hanoi_games.dat");
        
        if (gamesSavedHanoi == null){
            System.out.println("El arreglo esta vacio");
        } else {
            for (int i = 0; i < gamesSavedHanoi.size(); i++){
                System.out.println("---> "+gamesSavedHanoi.get(i).toString());
            }
        }
    }
    public static ArrayList<User> getUsersHanoi() {
        return usersHanoi;
    }

    public static void setUsersHanoi(ArrayList<User> users) {
        MenuHanoi.usersHanoi = users;
    }

    public static ArrayList<SaveGame> getGamesSavedHanoi() {
        return gamesSavedHanoi;
    }

    public static void setGamesSavedHanoi(ArrayList<SaveGame> gamesSaved) {
        MenuHanoi.gamesSavedHanoi = gamesSaved;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        gameButton = new javax.swing.JButton();
        statsButton = new javax.swing.JButton();
        playerButton = new javax.swing.JButton();
        playerTurnLabel = new javax.swing.JLabel();
        separatorLine3 = new javax.swing.JSeparator();
        playerTurnLabel1 = new javax.swing.JLabel();
        playerTurnLabel2 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        background.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBackground(new java.awt.Color(51, 51, 51));
        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoLabel.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("MENU");
        infoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoPanel.add(infoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 200, 30));

        gameButton.setBackground(new java.awt.Color(0, 51, 204));
        gameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        gameButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameButtonActionPerformed(evt);
            }
        });
        infoPanel.add(gameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 100, 100));

        statsButton.setBackground(new java.awt.Color(51, 0, 255));
        statsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        statsButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsButtonActionPerformed(evt);
            }
        });
        infoPanel.add(statsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 100, 100));

        playerButton.setBackground(new java.awt.Color(102, 51, 0));
        playerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        playerButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        playerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerButtonActionPerformed(evt);
            }
        });
        infoPanel.add(playerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 100, 100));

        playerTurnLabel.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        playerTurnLabel.setForeground(new java.awt.Color(255, 255, 255));
        playerTurnLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerTurnLabel.setText("REPORTES");
        playerTurnLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoPanel.add(playerTurnLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 160, 30));

        separatorLine3.setBackground(new java.awt.Color(255, 255, 255));
        separatorLine3.setForeground(new java.awt.Color(255, 255, 255));
        infoPanel.add(separatorLine3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 200, 20));

        playerTurnLabel1.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        playerTurnLabel1.setForeground(new java.awt.Color(255, 255, 255));
        playerTurnLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerTurnLabel1.setText("EMPEZAR A JUGAR");
        playerTurnLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoPanel.add(playerTurnLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 160, 30));

        playerTurnLabel2.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        playerTurnLabel2.setForeground(new java.awt.Color(255, 255, 255));
        playerTurnLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerTurnLabel2.setText("CREAR JUGADOR");
        playerTurnLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoPanel.add(playerTurnLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 160, 30));

        background.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 420, 580));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images_Hanoi/hanoiBG.jpg"))); // NOI18N
        bgLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        background.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playerButtonActionPerformed
        CreateUser player = new CreateUser();
        player.setVisible(true);
        ID = 1;
        this.dispose();
    }//GEN-LAST:event_playerButtonActionPerformed

    private void gameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameButtonActionPerformed
        SelectPlayerHanoi selectPlayer = new SelectPlayerHanoi();
        selectPlayer.setVisible(true);
        ID = 1;
        this.dispose();
    }//GEN-LAST:event_gameButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (ID == 0){
            PrincipalGUI principal = new PrincipalGUI();
            principal.setVisible(true);
        }
        
    }//GEN-LAST:event_formWindowClosed

    private void statsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsButtonActionPerformed
        StatsHanoi stats =  new StatsHanoi();
        stats.setVisible(true);
        ID = 1;
        this.dispose();
    }//GEN-LAST:event_statsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MenuHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MenuHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MenuHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MenuHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuHanoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JButton gameButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton playerButton;
    private javax.swing.JLabel playerTurnLabel;
    private javax.swing.JLabel playerTurnLabel1;
    private javax.swing.JLabel playerTurnLabel2;
    private javax.swing.JSeparator separatorLine3;
    private javax.swing.JButton statsButton;
    // End of variables declaration//GEN-END:variables
}
