package com.gui.hanoi;

import com.gui.checkers.options.*;
import com.gui.checkers.options.OptionGameType;
import com.gui.checkers.principals.MenuCheckersGUI;
import com.functionalities.utilities.files.User;
import com.gui.checkers.principals.BoardGUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author erik-lopez
 * 
 */
public class SelectPlayerHanoi extends javax.swing.JFrame {
    public static User userHanoi;
    
    int option, counter;
    private int ID;
    /**
     * Creates new form SelectPlayer
     * 
     */
    public SelectPlayerHanoi() {
        initComponents();
        ID = 0;
        counter = 1;
        extraComponents();
        startButton.setEnabled(false);
        this.setLocationRelativeTo(null);
    }

    public static User getUser1() {
        return userHanoi;
    }

    public static void setUser1(User user1) {
        SelectPlayerHanoi.userHanoi = user1;
    }

    public void extraComponents() {
        option = OptionGameType.getTypeGame();
        fillTable();
    }
    
    
    public void fillTable(){
        DefaultTableModel model = new DefaultTableModel(new String[]{"ID Jugador","Nombre del Jugador"},MenuHanoi.getUsersHanoi().size());
        playersTable.setModel(model);
        
        TableModel modelData = playersTable.getModel();
        
        for (int i = 0; i < MenuHanoi.getUsersHanoi().size(); i++) {
            User user = MenuHanoi.getUsersHanoi().get(i);
            modelData.setValueAt(user.getID(), i, 0);
            modelData.setValueAt(user.getName(), i, 1);
        }
    }
    
    public void optionsPlayer(int row) {
        userHanoi = MenuHanoi.getUsersHanoi().get(row);
        counter = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        selectButton = new javax.swing.JButton();
        infoLabel7 = new javax.swing.JLabel();
        playersPanel = new javax.swing.JPanel();
        scrollPlayerPanel = new javax.swing.JScrollPane();
        playersTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        infoLabel6 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SELECCION DE JUGADOR");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBackground(new java.awt.Color(51, 51, 51));
        infoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        infoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        typeLabel.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        typeLabel.setText("UN JUGADOR");
        typeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoPanel.add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 150, 30));

        selectButton.setBackground(new java.awt.Color(102, 102, 0));
        selectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        selectButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });
        infoPanel.add(selectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, 100));

        infoLabel7.setFont(new java.awt.Font("Chandas", 3, 14)); // NOI18N
        infoLabel7.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel7.setText("SELECCIONE");
        infoLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infoPanel.add(infoLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 150, 30));

        background.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 390, 130));

        playersPanel.setBackground(new java.awt.Color(51, 51, 51));
        playersPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrollPlayerPanel.setBackground(new java.awt.Color(51, 51, 51));
        scrollPlayerPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        playersTable.setBackground(new java.awt.Color(51, 51, 51));
        playersTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        playersTable.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        playersTable.setForeground(new java.awt.Color(255, 255, 255));
        playersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Jugador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        playersTable.setToolTipText("");
        playersTable.setDragEnabled(true);
        playersTable.setGridColor(new java.awt.Color(51, 51, 51));
        playersTable.setName(""); // NOI18N
        playersTable.setOpaque(false);
        playersTable.setRowHeight(25);
        playersTable.setSelectionForeground(new java.awt.Color(51, 0, 204));
        scrollPlayerPanel.setViewportView(playersTable);

        playersPanel.add(scrollPlayerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 280));

        background.add(playersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 390, 280));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startButton.setBackground(new java.awt.Color(0, 102, 153));
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images/utilities/click2.png"))); // NOI18N
        startButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        jPanel1.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, 100));

        infoLabel6.setFont(new java.awt.Font("Chandas", 1, 12)); // NOI18N
        infoLabel6.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        infoLabel6.setText("COMENZAR");
        infoLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(infoLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, 30));

        background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 390, 120));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/images_Hanoi/hanoiBG.jpg"))); // NOI18N
        bgLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        background.add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        int row = playersTable.getSelectedRow();
        
        if (row >= 0) {
            if (counter > 0) {
                optionsPlayer(row);
            }
            if (counter <= 0) {
                startButton.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_selectButtonActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        HanoiGUI hanoi = new HanoiGUI();
        hanoi.setVisible(true);
        ID = 1;
        this.dispose();
    }//GEN-LAST:event_startButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if (ID == 0){
            MenuHanoi menuHanoi = new MenuHanoi();
            menuHanoi.setVisible(true);
        }
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SelectPlayerHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SelectPlayerHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SelectPlayerHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SelectPlayerHanoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectPlayerHanoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel infoLabel6;
    private javax.swing.JLabel infoLabel7;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel playersPanel;
    private javax.swing.JTable playersTable;
    private javax.swing.JScrollPane scrollPlayerPanel;
    private javax.swing.JButton selectButton;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
